name: Build and Push to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_CLIENT_REPOSITORY: shopsmart-client
  ECR_SERVER_REPOSITORY: shopsmart-server
  BACKEND_URL: ${{ secrets.BACKEND_URL }}

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Client image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build \
          --build-arg VITE_API_URL=${{ secrets.BACKEND_URL }} \
          -t $ECR_REGISTRY/$ECR_CLIENT_REPOSITORY:$IMAGE_TAG ./client
        docker tag $ECR_REGISTRY/$ECR_CLIENT_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_CLIENT_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_CLIENT_REPOSITORY:latest

    - name: Build, tag, and push Server image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_SERVER_REPOSITORY:$IMAGE_TAG ./server
        docker tag $ECR_REGISTRY/$ECR_SERVER_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_SERVER_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_SERVER_REPOSITORY:latest
